language: ruby

rvm:
  - 3.3.6
  - 3.3.5
  - 3.3.4
  - 3.3.3

install: bundle install --retry=3

before_install:
  - gem update bundler

env:
  - 'TEST_RAILS_VERSION="~> 5.2.8"'
  - 'TEST_RAILS_VERSION="~> 6.1.7"'
  - 'TEST_RAILS_VERSION="~> 7.2.2"'
  - 'TEST_RAILS_VERSION="~> 8.0.0"'

script:
  - bundle exec rake test
  - rubocop app lib --fail-level R

matrix:
  allow_failures:
    - env: "RAILS_VERSION=master"