language: ruby

# Specify Ruby versions to test against
rvm:
  - 3.6
  - 3.5
  - 3.4
  - 3.3
  - 3.2
  - 3.1
  - 3.0

gemfile: gemfiles/Gemfile

before_install:
  - gem update --system
  - gem install bundler

script: bundle exec rake

cache: bundler

env:
  - 'TEST_RAILS_VERSION="~> 5.2.8"'
  - 'TEST_RAILS_VERSION="~> 6.1.7"'
  - 'TEST_RAILS_VERSION="~> 7.2.2"'
  - 'TEST_RAILS_VERSION="~> 8.0.0"'