---
name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  rspec:
    name: >-
      rspec (${{ matrix.ruby }})

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 3.3
          - 3.2
          - 3.1
        rails:
          - 7.2
        include:
          # Edge
          - { ruby: 'head', rails: 'edge', allow-fail: true }
          # Outdated
          - { ruby: '3.0',  rails: '7.1' }

    env:
      RAILS_VERSION: "${{ matrix.rails }}"

    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          rubygems: latest
          bundler-cache: true

      - name: >-
          Test ${{ steps.test.outcome }}
        run: |
          echo Ruby  ${{ matrix.ruby  }}
          echo Rails ${{ matrix.rails }}

      - name: Analyze code
        run: bundle exec rubocop

      - name: Setup DB, Run tests
        env:
          RAILS_ENV: test
        run: |
          bin/rails db:create db:schema:load
          bundle exec rspec